### ISSUE TITLE
Error provisioning: "No resource or method named `apt_repository' for `Chef::Recipe "apt_repository"'"

### ISSUE THREAD

**Issue by luke83** [FriendsOfCake/vagrant-chef#49]
I got following error when i try to provisioning an already provisioned (and working) vagrant machine:

```
$ vagrant provision
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2016-08-23T17:03:39+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.7.2
==> default: [2016-08-23T17:03:39+00:00] INFO: *** Chef 12.7.2 ***
==> default: [2016-08-23T17:03:39+00:00] INFO: Chef-client pid: 3190
==> default: [2016-08-23T17:03:41+00:00] INFO: Setting the run_list to ["role[vagrant]"] from CLI options
==> default: [2016-08-23T17:03:41+00:00] INFO: Run List is [role[vagrant]]
==> default: [2016-08-23T17:03:41+00:00] INFO: Run List expands to [system::init, system::update, hostname::default, git::install, percona::install, postgresql::install, redis::install, memcached::install, nginx::server, ruby::install, php::install, cakephp::setup]
==> default: [2016-08-23T17:03:41+00:00] INFO: Starting Chef Run for vagrant-336a60fa
==> default: [2016-08-23T17:03:41+00:00] INFO: Running start handlers
==> default: [2016-08-23T17:03:41+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/install.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: No resource or method named `apt_repository' for `Chef::Recipe "apt_repository"'
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/apt_repository.rb:1:in `from_file'
==> default:
==> default:   /tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/install.rb:1:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/apt_repository.rb:
==> default:
==> default:
==> default:
==> default:   1>> apt_repository "git" do
==> default:
==> default:   2:    key "E1DF1F24"
==> default:
==> default:   3:    uri "ppa:git-core/ppa"
==> default:
==> default:   4:    distribution node["lsb"]["codename"]
==> default:
==> default:   5:  end
==> default:
==> default:   6:
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2016-08-23T17:03:41+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-08-23T17:03:41+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 01 seconds
==> default: [2016-08-23T17:03:41+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-23T17:03:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-23T17:03:41+00:00] ERROR: No resource or method named `apt_repository' for `Chef::Recipe "apt_repository"'
==> default: [2016-08-23T17:03:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

This is the stacktrace dump mentioned in the FATAL above:

```
Generated at 2016-08-23 16:56:45 +0000
NoMethodError: No resource or method named `apt_repository' for `Chef::Recipe "apt_repository"'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/dsl/recipe.rb:102:in `rescue in method_missing'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/dsl/recipe.rb:99:in `method_missing'
/tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/apt_repository.rb:1:in `from_file'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/cookbook_version.rb:229:in `load_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:332:in `load_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:288:in `block in include_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:287:in `each'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:287:in `include_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/tmp/vagrant-chef/795bb757d3bb74dcdc0c581c11db1c17/cookbooks/git/recipes/install.rb:1:in `from_file'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/cookbook_version.rb:229:in `load_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:332:in `load_recipe'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/run_context.rb:167:in `load'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/policy_builder/expand_node_object.rb:93:in `setup_run_context'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/client.rb:509:in `setup_run_context'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/client.rb:277:in `run'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application/solo.rb:297:in `block in interval_run_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application/solo.rb:286:in `loop'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application/solo.rb:286:in `interval_run_chef_client'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application/solo.rb:265:in `run_application'
/var/lib/gems/2.2.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'
/var/lib/gems/2.2.0/gems/chef-12.7.2/bin/chef-solo:25:in `<top (required)>'
/usr/local/bin/chef-solo:23:in `load'
/usr/local/bin/chef-solo:23:in `<main>'
```

I'm a little noob in vagrant+chef, any clue is (really) appreciated xD

**Comment by josegonzalez** [comment]
Destroy the VM and bring it back up. The new version changed quite a few things.

That or checkout the release before latest.

**Comment by luke83** [comment]
Thanks Jose, i destroyed vm, updated to last vagrant (just in case..), than fired `vagrant up` and i got still errors:

```
==> default:     ================================================================================

==> default:     Error executing action `upgrade` on resource 'gem_package[pusher-client]'
==> default:     ================================================================================

==> default:
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '2'
==> default:     ---- Begin output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
==> default:     STDOUT:
==> default:     STDERR: ERROR:  Could not find a valid gem 'pusher-client' (= 1.2.3) in any repository
==> default:     ERROR:  Possible alternatives: pusher-client
==> default:     ---- End output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
==> default:     Ran /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose returned 2
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/ruby/recipes/install.rb
==> default:
==> default:      49:   gem_package g do
==> default:      50:     gem_binary("/usr/bin/gem")
==> default:      51:     options "--no-ri --no-rdoc --verbose"
==> default:      52:     action :upgrade
==> default:      53:   end
==> default:      54: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/ruby/recipes/install.rb:49:in `block in from_file'
==> default:
==> default:     gem_package("pusher-client") do
==> default:       package_name "pusher-client"
==> default:       action [:upgrade]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :gem_package
==> default:       cookbook_name "ruby"
==> default:       recipe_name "install"
==> default:       gem_binary "/usr/bin/gem"
==> default:       options "--no-ri --no-rdoc --verbose"
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default: [2016-08-23T19:51:08+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2016-08-23T19:51:08+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-08-23T19:51:08+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 1 resources updated in 23 seconds
==> default: [2016-08-23T19:51:08+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-23T19:51:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-23T19:51:08+00:00] ERROR: gem_package[pusher-client] (ruby::install line 49) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
==> default: ---- Begin output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
==> default: STDOUT:
==> default: STDERR: ERROR:  Could not find a valid gem 'pusher-client' (= 1.2.3) in any repository
==> default: ERROR:  Possible alternatives: pusher-client
==> default: ---- End output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
==> default: Ran /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose returned 2
==> default: [2016-08-23T19:51:08+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
stacktrace dumped:

```
Generated at 2016-08-23 19:51:08 +0000
Mixlib::ShellOut::ShellCommandFailed: gem_package[pusher-client] (ruby::install line 49) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
STDOUT:
STDERR: ERROR:  Could not find a valid gem 'pusher-client' (= 1.2.3) in any repository
ERROR:  Possible alternatives: pusher-client
---- End output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
Ran /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose returned 2
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:576:in `shell_out_with_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:549:in `install_via_gem_command'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:529:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:556:in `upgrade_package'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:127:in `block (2 levels) in action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:227:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:126:in `block in action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:125:in `action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/solo.rb:226:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:53:in `load'
/usr/bin/chef-solo:53:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
STDOUT:
STDERR: ERROR:  Could not find a valid gem 'pusher-client' (= 1.2.3) in any repository
ERROR:  Possible alternatives: pusher-client
---- End output of /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose ----
Ran /usr/bin/gem install pusher-client -q --no-rdoc --no-ri -v "1.2.3" --no-ri --no-rdoc --verbose returned 2
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:576:in `shell_out_with_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:549:in `install_via_gem_command'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:529:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package/rubygems.rb:556:in `upgrade_package'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:127:in `block (2 levels) in action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:227:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:126:in `block in action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider/package.rb:125:in `action_upgrade'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/lib/chef/application/solo.rb:226:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.16/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:53:in `load'
/usr/bin/chef-solo:53:in `<main>'
```

**Comment by luke83** [comment]
another try with a clean run today did the job, sorry for time...
