### ISSUE TITLE
Error after git pull origin master and 

### ISSUE THREAD

**Issue by KieranYo** [FriendsOfCake/vagrant-chef#56]
Background: I noticed that my master branch was 2 commits behind the remote and decided to switch to Multiple Repositories.

After running the following:

```
git pull origin master
vagrant reload --provision
```

Here's the output

```bash
==> default: [vagrant-hostsupdater] Removing hosts
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: A newer version of the box 'bento/ubuntu-14.04' is available! You currently
==> default: have version '2.3.1'. The latest is version '2.3.4'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.18 running --- OK.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/kbm/Sites/www/me_too_and_co/web
    default: /tmp/vagrant-chef/e4cbceee618c84ec0a370ffc3a2cb1fb/roles => /Users/kbm/Sites/www/me_too_and_co/web/cookbooks/roles
    default: /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks => /Users/kbm/Sites/www/me_too_and_co/web/cookbooks
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: [2017-03-31T09:20:25+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.7.2
==> default: [2017-03-31T09:20:25+00:00] INFO: *** Chef 12.7.2 ***
==> default: [2017-03-31T09:20:25+00:00] INFO: Chef-client pid: 2481
==> default: [2017-03-31T09:20:27+00:00] INFO: Setting the run_list to ["role[vagrant]"] from CLI options
==> default: [2017-03-31T09:20:27+00:00] INFO: Run List is [role[vagrant]]
==> default: [2017-03-31T09:20:27+00:00] INFO: Run List expands to [system::init, system::update, hostname::default, git::install, percona::install, postgresql::install, redis::install, memcached::install, nginx::server, ruby::install, php::install, cakephp::setup]
==> default: [2017-03-31T09:20:27+00:00] INFO: Starting Chef Run for vagrant-227cc076
==> default: [2017-03-31T09:20:27+00:00] INFO: Running start handlers
==> default: [2017-03-31T09:20:27+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks/git/recipes/install.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `uri' for Custom resource apt_repository from cookbook apt
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks/git/recipes/apt_repository.rb:3:in `block in from_file'
==> default:
==> default:   /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks/git/recipes/apt_repository.rb:1:in `from_file'
==> default:
==> default:   /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks/git/recipes/install.rb:1:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/aa182ebd466f84178fd6ac3d6f567090/cookbooks/git/recipes/apt_repository.rb:
==> default:
==> default:   1:  apt_repository "git" do
==> default:   2:    key "E1DF1F24"
==> default:   3>>   uri "ppa:git-core/ppa"
==> default:   4:    distribution node["lsb"]["codename"]
==> default:   5:  end
==> default:   6:
==> default:
==> default:
==> default: Running handlers:
==> default: [2017-03-31T09:20:27+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-03-31T09:20:27+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 02 seconds
==> default: [2017-03-31T09:20:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-03-31T09:20:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-03-31T09:20:27+00:00] ERROR: undefined method `uri' for Custom resource apt_repository from cookbook apt
==> default: [2017-03-31T09:20:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by KieranYo** [comment]
After `vagrant destroy`ing the box and starting again I no longer get this issue.
