### ISSUE TITLE
Issue with `vagrant up`

### ISSUE THREAD

**Issue by KieranYo** [FriendsOfCake/vagrant-chef#72]
I'm getting the following error when running `vagrant up`

Host machine: Windows 10.

Funny enough it works just fine on my Mac.

```
Mixlib::ShellOut::ShellCommandFailed: apt_package[postgresql-client-9.6] (postgresql::client line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-client-9.6 : Depends: libpq5 (>= 9.6.8) but 9.5.12-0ubuntu0.16.04 is to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] ----
Ran ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:293:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:280:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:120:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:76:in `shell_out_compact!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:95:in `shell_out_compact_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/apt.rb:146:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/apt.rb:85:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:227:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:100:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:576:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:717:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:751:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/solo.rb:224:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:59:in `load'
/usr/bin/chef-solo:59:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-client-9.6 : Depends: libpq5 (>= 9.6.8) but 9.5.12-0ubuntu0.16.04 is to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] ----
Ran ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "postgresql-client-9.6=9.6.8-1.pgdg16.04+1"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:293:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:280:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:120:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:76:in `shell_out_compact!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/shell_out.rb:95:in `shell_out_compact_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/apt.rb:146:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/apt.rb:85:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:227:in `converge_by'
```

**Comment by KieranYo** [comment]
I've since got it working and submitted a pull request ^ above
